apply plugin: 'com.android.application'

android{
    namespace 'com.gumbyxgames.leankeykeyboard'

    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    compileSdk 37


    defaultConfig {
        applicationId "org.gumbyxgames.leankeykeyboard_handhelds"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.1"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            // Load local.properties in an object
            def localProperties = new Properties()
            localProperties.load(new FileInputStream(rootProject.file("local.properties")))
            // Use the object to access properties
            storeFile file(localProperties['STORE_FILE'])
            storePassword localProperties['STORE_PASSWORD']
            keyPassword localProperties['KEY_PASSWORD']
            keyAlias localProperties['KEY_ALIAS']
        }
    }

    buildTypes {
        release {
            minifyEnabled true // enable obfuscation
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def project = "leanKeyboard-handhelds"
            def buildType = variant.buildType.name
            def version = variant.versionName

            //def newApkName = sprintf("%s-v%s-%s.apk", project, version, buildType)
            //def newApkName = sprintf("%s-v%s.apk", project, version)
            //output.outputFileName = new File(newApkName)
        }
    }

    flavorDimensions "default"
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation rootProject.ext.junitVersion
    implementation rootProject.ext.appCompatXVersion
    implementation rootProject.ext.leanbackCompatXVersion
    implementation rootProject.ext.constraintXVersion
    implementation rootProject.ext.designXVersion
    implementation rootProject.ext.voiceOverlayVersion
}
