name: Create Github Release Build (APK and App Bundle)

on: workflow_dispatch

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Build Release bundle
        run: ./gradlew bundleRelease

      - name: List directory structure
        run: tree . -P "*.apk"

      - name: Upload Signed APKs
        uses: actions/upload-artifact@v7.0.1
        with:
          name: Signed-APK
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/bundle/release/app-bundle.abb

      - name: Create Github Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          generate_release_notes: true
          prerelease: false
#          name: release_build
          tag_name: release
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: app/build/outputs/apk/release/app-release.apk
