name: Testing Android APK Building

on: workflow_dispatch

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v7.0.1
        with:
          name: debug_build
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Decode Keystore
        env:
          KEY_STORE_ENCODED: ${{ secrets.KEY_STORE_BASE64 }}
        run: |
          echo $KEY_STORE_ENCODED > keystore-b64.txt
          base64 -d keystore-b64.txt > $KEY_STORE

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: List directory structure
        run: tree . -P "*.apk"

      - name: Sign APK
        run: |
              jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \ 
              -keystore $KEY_STORE -storepass ${{ KEY_STORE_PASSWORD }} \ 
              -keypass ${{ KEY_PASSWORD }} app/build/outputs/apk/release/app-release-unsigned.apk ${{ KEY_ALIAS }}

      - name: Verify signature
        run: jarsigner -verify -verbose -certs app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Align APK
        run: |
              $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 \
              app/build/outputs/apk/release/app-release-unsigned.apk \
              app/build/outputs/apk/release/app-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v7.0.1
        with:
              name: Signed-APK
              path: app/build/outputs/apk/release/app-release.apk

      - name: Create Github Release of prerelease APK
        uses: softprops/action-gh-release@v3.0.0
        with:
            generate_release_notes: false
            prerelease: true
            tag_name: test_release
            token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
            files: app/build/outputs/apk/release/app-release.apk