name: Testing Android APK Building

on: workflow_dispatch

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Secret Properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > ./local.properties

      - name: Prepare release keystore
        run: |
              echo "${{ secrets.KEY_STORE_BASE64 }}" > keystore-b64.txt
              base64 -d keystore-b64.txt > app/keystore.jks

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: List directory structure
        run: tree . -P "*.apk"

      - name: Upload Signed APKs
        uses: actions/upload-artifact@v7.0.1
        with:
              name: Signed-APK
              path: |
                    app/build/outputs/apk/release/app-release.apk
                    app/build/outputs/apk/debug/app-debug.apk

      - name: Create Github Release of prerelease APK
        uses: softprops/action-gh-release@v3.0.0locallocal
        with:
            generate_release_notes: false
            prerelease: true
            tag_name: test_release
            token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
            files: app/build/outputs/apk/release/app-release.apk